export const SUCCESS_MESSAGE = {
  LOGIN_SUCCESS: "Login successful!",
  REGISTER_SUCCESS: "Register successful!",
  VERIFY_OTP_SUCCESS: "Email verified successfully!",
  RESEND_OTP_SUCCESS: "OTP has been resent successfully!",
  RESET_PASSWORD_SUCCESS: "Password reset successfully!",
  FORGOT_PASSWORD_OTP_SENT: "OTP has been sent to your email!",
  PROFILE_UPDATED: "Profile updated successfully!",
  CREATE_SEMESTER_SUCCESS: "Semester created successfully!",
  UPDATE_SEMESTER_SUCCESS: "Semester updated successfully!",
  DELETE_SEMESTER_SUCCESS: "Semester deleted successfully!",
  CREATE_COMBO_SUCCESS: "Combo subject and its subjects created successfully!",
  UPDATE_COMBO_SUCCESS: "Combo subject updated successfully!",
  DELETE_COMBO_SUCCESS: "Combo subject and its subjects deleted successfully!",
  CREATE_SUBJECT_SUCCESS: "Subject added successfully to this combo!",
  UPDATE_SUBJECT_SUCCESS: "Subject updated successfully!",
  DELETE_SUBJECT_SUCCESS: "Subject deleted successfully from this combo!",
};
